// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Clan.proto

package com.randioo.shizurongyao_server.protocol;

public final class Clan {
  private Clan() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ClanShowAllClanRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use ClanShowAllClanRequest.newBuilder() to construct.
    private ClanShowAllClanRequest() {
      initFields();
    }
    private ClanShowAllClanRequest(boolean noInit) {}
    
    private static final ClanShowAllClanRequest defaultInstance;
    public static ClanShowAllClanRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClanShowAllClanRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shizurongyao_server.protocol.Clan.internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shizurongyao_server.protocol.Clan.internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest result;
      
      // Construct using com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest();
        return builder;
      }
      
      protected com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest.getDescriptor();
      }
      
      public com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest getDefaultInstanceForType() {
        return com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest) {
          return mergeFrom((com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest other) {
        if (other == com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shizurongyao_server.protocol.ClanShowAllClanRequest)
    }
    
    static {
      defaultInstance = new ClanShowAllClanRequest(true);
      com.randioo.shizurongyao_server.protocol.Clan.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shizurongyao_server.protocol.ClanShowAllClanRequest)
  }
  
  public static final class ClanShowAllClanResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use ClanShowAllClanResponse.newBuilder() to construct.
    private ClanShowAllClanResponse() {
      initFields();
    }
    private ClanShowAllClanResponse(boolean noInit) {}
    
    private static final ClanShowAllClanResponse defaultInstance;
    public static ClanShowAllClanResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClanShowAllClanResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shizurongyao_server.protocol.Clan.internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shizurongyao_server.protocol.Clan.internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanResponse_fieldAccessorTable;
    }
    
    // repeated .com.randioo.shizurongyao_server.protocol.ClanData clanData = 1;
    public static final int CLANDATA_FIELD_NUMBER = 1;
    private java.util.List<com.randioo.shizurongyao_server.protocol.Entity.ClanData> clanData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.shizurongyao_server.protocol.Entity.ClanData> getClanDataList() {
      return clanData_;
    }
    public int getClanDataCount() { return clanData_.size(); }
    public com.randioo.shizurongyao_server.protocol.Entity.ClanData getClanData(int index) {
      return clanData_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.randioo.shizurongyao_server.protocol.Entity.ClanData element : getClanDataList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.randioo.shizurongyao_server.protocol.Entity.ClanData element : getClanDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse result;
      
      // Construct using com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse();
        return builder;
      }
      
      protected com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse.getDescriptor();
      }
      
      public com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse getDefaultInstanceForType() {
        return com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.clanData_ != java.util.Collections.EMPTY_LIST) {
          result.clanData_ =
            java.util.Collections.unmodifiableList(result.clanData_);
        }
        com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse) {
          return mergeFrom((com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse other) {
        if (other == com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse.getDefaultInstance()) return this;
        if (!other.clanData_.isEmpty()) {
          if (result.clanData_.isEmpty()) {
            result.clanData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.ClanData>();
          }
          result.clanData_.addAll(other.clanData_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.shizurongyao_server.protocol.Entity.ClanData.Builder subBuilder = com.randioo.shizurongyao_server.protocol.Entity.ClanData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addClanData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.randioo.shizurongyao_server.protocol.ClanData clanData = 1;
      public java.util.List<com.randioo.shizurongyao_server.protocol.Entity.ClanData> getClanDataList() {
        return java.util.Collections.unmodifiableList(result.clanData_);
      }
      public int getClanDataCount() {
        return result.getClanDataCount();
      }
      public com.randioo.shizurongyao_server.protocol.Entity.ClanData getClanData(int index) {
        return result.getClanData(index);
      }
      public Builder setClanData(int index, com.randioo.shizurongyao_server.protocol.Entity.ClanData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.clanData_.set(index, value);
        return this;
      }
      public Builder setClanData(int index, com.randioo.shizurongyao_server.protocol.Entity.ClanData.Builder builderForValue) {
        result.clanData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addClanData(com.randioo.shizurongyao_server.protocol.Entity.ClanData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.clanData_.isEmpty()) {
          result.clanData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.ClanData>();
        }
        result.clanData_.add(value);
        return this;
      }
      public Builder addClanData(com.randioo.shizurongyao_server.protocol.Entity.ClanData.Builder builderForValue) {
        if (result.clanData_.isEmpty()) {
          result.clanData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.ClanData>();
        }
        result.clanData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllClanData(
          java.lang.Iterable<? extends com.randioo.shizurongyao_server.protocol.Entity.ClanData> values) {
        if (result.clanData_.isEmpty()) {
          result.clanData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.ClanData>();
        }
        super.addAll(values, result.clanData_);
        return this;
      }
      public Builder clearClanData() {
        result.clanData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shizurongyao_server.protocol.ClanShowAllClanResponse)
    }
    
    static {
      defaultInstance = new ClanShowAllClanResponse(true);
      com.randioo.shizurongyao_server.protocol.Clan.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shizurongyao_server.protocol.ClanShowAllClanResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nClan.proto\022(com.randioo.shizurongyao_s" +
      "erver.protocol\032\014Entity.proto\"\030\n\026ClanShow" +
      "AllClanRequest\"_\n\027ClanShowAllClanRespons" +
      "e\022D\n\010clanData\030\001 \003(\01322.com.randioo.shizur" +
      "ongyao_server.protocol.ClanData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanRequest_descriptor,
              new java.lang.String[] { },
              com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest.class,
              com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanRequest.Builder.class);
          internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shizurongyao_server_protocol_ClanShowAllClanResponse_descriptor,
              new java.lang.String[] { "ClanData", },
              com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse.class,
              com.randioo.shizurongyao_server.protocol.Clan.ClanShowAllClanResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.shizurongyao_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
