// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Error.proto

package com.randioo.shizurongyao_server.protocol;

public final class Error {
  private Error() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    OK(0, 1),
    NO_STRING(1, 2),
    NO_ROLE_ACCOUNT(2, 3),
    EXIST_ROLE(3, 4),
    CREATE_FAILED(4, 5),
    REJECT_LOGIN(5, 6),
    ACCOUNT_ILLEGEL(6, 7),
    IN_LOGIN(7, 8),
    NAME_SENSITIVE(8, 9),
    NO_ROLE_DATA(9, 10),
    NAME_REPEATED(10, 11),
    NAME_TOO_LONG(11, 12),
    NAME_SPECIAL_CHAR(12, 13),
    NO_CARD(13, 14),
    NO_MONEY(14, 15),
    NO_GOLD(15, 16),
    ERR_CANCEL_ROOM(16, 17),
    ERR_TYPE_MAIN_ID(17, 18),
    OUT_INDEX_OF(18, 19),
    ERR_NUM_CARD_H(19, 20),
    ERR_NUM_CARD_N(20, 21),
    MAX_CARD_LV(21, 22),
    NO_MARCH_TARGET(22, 23),
    CHAPTER_AWARD_NEED_STAR_FULL(23, 24),
    REPEAT_GET_AWARD(24, 25),
    RACE_NUM_FULL(25, 26),
    RACE_NOT_SIGN_UP(26, 27),
    RACE_BEEN_SIGN_UP(27, 28),
    RACE_BEEN_NOT_SIGN_UP(28, 29),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static ErrorCode valueOf(int value) {
      switch (value) {
        case 1: return OK;
        case 2: return NO_STRING;
        case 3: return NO_ROLE_ACCOUNT;
        case 4: return EXIST_ROLE;
        case 5: return CREATE_FAILED;
        case 6: return REJECT_LOGIN;
        case 7: return ACCOUNT_ILLEGEL;
        case 8: return IN_LOGIN;
        case 9: return NAME_SENSITIVE;
        case 10: return NO_ROLE_DATA;
        case 11: return NAME_REPEATED;
        case 12: return NAME_TOO_LONG;
        case 13: return NAME_SPECIAL_CHAR;
        case 14: return NO_CARD;
        case 15: return NO_MONEY;
        case 16: return NO_GOLD;
        case 17: return ERR_CANCEL_ROOM;
        case 18: return ERR_TYPE_MAIN_ID;
        case 19: return OUT_INDEX_OF;
        case 20: return ERR_NUM_CARD_H;
        case 21: return ERR_NUM_CARD_N;
        case 22: return MAX_CARD_LV;
        case 23: return NO_MARCH_TARGET;
        case 24: return CHAPTER_AWARD_NEED_STAR_FULL;
        case 25: return REPEAT_GET_AWARD;
        case 26: return RACE_NUM_FULL;
        case 27: return RACE_NOT_SIGN_UP;
        case 28: return RACE_BEEN_SIGN_UP;
        case 29: return RACE_BEEN_NOT_SIGN_UP;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.randioo.shizurongyao_server.protocol.Error.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ErrorCode[] VALUES = {
      OK, NO_STRING, NO_ROLE_ACCOUNT, EXIST_ROLE, CREATE_FAILED, REJECT_LOGIN, ACCOUNT_ILLEGEL, IN_LOGIN, NAME_SENSITIVE, NO_ROLE_DATA, NAME_REPEATED, NAME_TOO_LONG, NAME_SPECIAL_CHAR, NO_CARD, NO_MONEY, NO_GOLD, ERR_CANCEL_ROOM, ERR_TYPE_MAIN_ID, OUT_INDEX_OF, ERR_NUM_CARD_H, ERR_NUM_CARD_N, MAX_CARD_LV, NO_MARCH_TARGET, CHAPTER_AWARD_NEED_STAR_FULL, REPEAT_GET_AWARD, RACE_NUM_FULL, RACE_NOT_SIGN_UP, RACE_BEEN_SIGN_UP, RACE_BEEN_NOT_SIGN_UP, 
    };
    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private ErrorCode(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      com.randioo.shizurongyao_server.protocol.Error.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:com.randioo.shizurongyao_server.protocol.ErrorCode)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Error.proto\022(com.randioo.shizurongyao_" +
      "server.protocol*\270\004\n\tErrorCode\022\006\n\002OK\020\001\022\r\n" +
      "\tNO_STRING\020\002\022\023\n\017NO_ROLE_ACCOUNT\020\003\022\016\n\nEXI" +
      "ST_ROLE\020\004\022\021\n\rCREATE_FAILED\020\005\022\020\n\014REJECT_L" +
      "OGIN\020\006\022\023\n\017ACCOUNT_ILLEGEL\020\007\022\014\n\010IN_LOGIN\020" +
      "\010\022\022\n\016NAME_SENSITIVE\020\t\022\020\n\014NO_ROLE_DATA\020\n\022" +
      "\021\n\rNAME_REPEATED\020\013\022\021\n\rNAME_TOO_LONG\020\014\022\025\n" +
      "\021NAME_SPECIAL_CHAR\020\r\022\013\n\007NO_CARD\020\016\022\014\n\010NO_" +
      "MONEY\020\017\022\013\n\007NO_GOLD\020\020\022\023\n\017ERR_CANCEL_ROOM\020" +
      "\021\022\024\n\020ERR_TYPE_MAIN_ID\020\022\022\020\n\014OUT_INDEX_OF\020",
      "\023\022\022\n\016ERR_NUM_CARD_H\020\024\022\022\n\016ERR_NUM_CARD_N\020" +
      "\025\022\017\n\013MAX_CARD_LV\020\026\022\023\n\017NO_MARCH_TARGET\020\027\022" +
      " \n\034CHAPTER_AWARD_NEED_STAR_FULL\020\030\022\024\n\020REP" +
      "EAT_GET_AWARD\020\031\022\021\n\rRACE_NUM_FULL\020\032\022\024\n\020RA" +
      "CE_NOT_SIGN_UP\020\033\022\025\n\021RACE_BEEN_SIGN_UP\020\034\022" +
      "\031\n\025RACE_BEEN_NOT_SIGN_UP\020\035"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
