// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Game.proto

package com.randioo.shizurongyao_server.protocol;

public final class Game {
  private Game() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class GameAction extends
      com.google.protobuf.GeneratedMessage {
    // Use GameAction.newBuilder() to construct.
    private GameAction() {
      initFields();
    }
    private GameAction(boolean noInit) {}
    
    private static final GameAction defaultInstance;
    public static GameAction getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameAction getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shizurongyao_server.protocol.Game.internal_static_com_randioo_shizurongyao_server_protocol_GameAction_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shizurongyao_server.protocol.Game.internal_static_com_randioo_shizurongyao_server_protocol_GameAction_fieldAccessorTable;
    }
    
    // optional int32 step = 1;
    public static final int STEP_FIELD_NUMBER = 1;
    private boolean hasStep;
    private int step_ = 0;
    public boolean hasStep() { return hasStep; }
    public int getStep() { return step_; }
    
    // optional int32 playerId = 2;
    public static final int PLAYERID_FIELD_NUMBER = 2;
    private boolean hasPlayerId;
    private int playerId_ = 0;
    public boolean hasPlayerId() { return hasPlayerId; }
    public int getPlayerId() { return playerId_; }
    
    // optional int32 cardId = 3;
    public static final int CARDID_FIELD_NUMBER = 3;
    private boolean hasCardId;
    private int cardId_ = 0;
    public boolean hasCardId() { return hasCardId; }
    public int getCardId() { return cardId_; }
    
    // optional int32 previewId = 4;
    public static final int PREVIEWID_FIELD_NUMBER = 4;
    private boolean hasPreviewId;
    private int previewId_ = 0;
    public boolean hasPreviewId() { return hasPreviewId; }
    public int getPreviewId() { return previewId_; }
    
    // optional int32 x = 5;
    public static final int X_FIELD_NUMBER = 5;
    private boolean hasX;
    private int x_ = 0;
    public boolean hasX() { return hasX; }
    public int getX() { return x_; }
    
    // optional int32 y = 6;
    public static final int Y_FIELD_NUMBER = 6;
    private boolean hasY;
    private int y_ = 0;
    public boolean hasY() { return hasY; }
    public int getY() { return y_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasStep()) {
        output.writeInt32(1, getStep());
      }
      if (hasPlayerId()) {
        output.writeInt32(2, getPlayerId());
      }
      if (hasCardId()) {
        output.writeInt32(3, getCardId());
      }
      if (hasPreviewId()) {
        output.writeInt32(4, getPreviewId());
      }
      if (hasX()) {
        output.writeInt32(5, getX());
      }
      if (hasY()) {
        output.writeInt32(6, getY());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasStep()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getStep());
      }
      if (hasPlayerId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getPlayerId());
      }
      if (hasCardId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getCardId());
      }
      if (hasPreviewId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getPreviewId());
      }
      if (hasX()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getX());
      }
      if (hasY()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, getY());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shizurongyao_server.protocol.Game.GameAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Game.GameAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Game.GameAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Game.GameAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Game.GameAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Game.GameAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Game.GameAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Game.GameAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Game.GameAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Game.GameAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shizurongyao_server.protocol.Game.GameAction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shizurongyao_server.protocol.Game.GameAction result;
      
      // Construct using com.randioo.shizurongyao_server.protocol.Game.GameAction.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shizurongyao_server.protocol.Game.GameAction();
        return builder;
      }
      
      protected com.randioo.shizurongyao_server.protocol.Game.GameAction internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shizurongyao_server.protocol.Game.GameAction();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shizurongyao_server.protocol.Game.GameAction.getDescriptor();
      }
      
      public com.randioo.shizurongyao_server.protocol.Game.GameAction getDefaultInstanceForType() {
        return com.randioo.shizurongyao_server.protocol.Game.GameAction.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shizurongyao_server.protocol.Game.GameAction build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shizurongyao_server.protocol.Game.GameAction buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shizurongyao_server.protocol.Game.GameAction buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shizurongyao_server.protocol.Game.GameAction returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shizurongyao_server.protocol.Game.GameAction) {
          return mergeFrom((com.randioo.shizurongyao_server.protocol.Game.GameAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shizurongyao_server.protocol.Game.GameAction other) {
        if (other == com.randioo.shizurongyao_server.protocol.Game.GameAction.getDefaultInstance()) return this;
        if (other.hasStep()) {
          setStep(other.getStep());
        }
        if (other.hasPlayerId()) {
          setPlayerId(other.getPlayerId());
        }
        if (other.hasCardId()) {
          setCardId(other.getCardId());
        }
        if (other.hasPreviewId()) {
          setPreviewId(other.getPreviewId());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setStep(input.readInt32());
              break;
            }
            case 16: {
              setPlayerId(input.readInt32());
              break;
            }
            case 24: {
              setCardId(input.readInt32());
              break;
            }
            case 32: {
              setPreviewId(input.readInt32());
              break;
            }
            case 40: {
              setX(input.readInt32());
              break;
            }
            case 48: {
              setY(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 step = 1;
      public boolean hasStep() {
        return result.hasStep();
      }
      public int getStep() {
        return result.getStep();
      }
      public Builder setStep(int value) {
        result.hasStep = true;
        result.step_ = value;
        return this;
      }
      public Builder clearStep() {
        result.hasStep = false;
        result.step_ = 0;
        return this;
      }
      
      // optional int32 playerId = 2;
      public boolean hasPlayerId() {
        return result.hasPlayerId();
      }
      public int getPlayerId() {
        return result.getPlayerId();
      }
      public Builder setPlayerId(int value) {
        result.hasPlayerId = true;
        result.playerId_ = value;
        return this;
      }
      public Builder clearPlayerId() {
        result.hasPlayerId = false;
        result.playerId_ = 0;
        return this;
      }
      
      // optional int32 cardId = 3;
      public boolean hasCardId() {
        return result.hasCardId();
      }
      public int getCardId() {
        return result.getCardId();
      }
      public Builder setCardId(int value) {
        result.hasCardId = true;
        result.cardId_ = value;
        return this;
      }
      public Builder clearCardId() {
        result.hasCardId = false;
        result.cardId_ = 0;
        return this;
      }
      
      // optional int32 previewId = 4;
      public boolean hasPreviewId() {
        return result.hasPreviewId();
      }
      public int getPreviewId() {
        return result.getPreviewId();
      }
      public Builder setPreviewId(int value) {
        result.hasPreviewId = true;
        result.previewId_ = value;
        return this;
      }
      public Builder clearPreviewId() {
        result.hasPreviewId = false;
        result.previewId_ = 0;
        return this;
      }
      
      // optional int32 x = 5;
      public boolean hasX() {
        return result.hasX();
      }
      public int getX() {
        return result.getX();
      }
      public Builder setX(int value) {
        result.hasX = true;
        result.x_ = value;
        return this;
      }
      public Builder clearX() {
        result.hasX = false;
        result.x_ = 0;
        return this;
      }
      
      // optional int32 y = 6;
      public boolean hasY() {
        return result.hasY();
      }
      public int getY() {
        return result.getY();
      }
      public Builder setY(int value) {
        result.hasY = true;
        result.y_ = value;
        return this;
      }
      public Builder clearY() {
        result.hasY = false;
        result.y_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shizurongyao_server.protocol.GameAction)
    }
    
    static {
      defaultInstance = new GameAction(true);
      com.randioo.shizurongyao_server.protocol.Game.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shizurongyao_server.protocol.GameAction)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shizurongyao_server_protocol_GameAction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shizurongyao_server_protocol_GameAction_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nGame.proto\022(com.randioo.shizurongyao_s" +
      "erver.protocol\"e\n\nGameAction\022\014\n\004step\030\001 \001" +
      "(\005\022\020\n\010playerId\030\002 \001(\005\022\016\n\006cardId\030\003 \001(\005\022\021\n\t" +
      "previewId\030\004 \001(\005\022\t\n\001x\030\005 \001(\005\022\t\n\001y\030\006 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_shizurongyao_server_protocol_GameAction_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_shizurongyao_server_protocol_GameAction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shizurongyao_server_protocol_GameAction_descriptor,
              new java.lang.String[] { "Step", "PlayerId", "CardId", "PreviewId", "X", "Y", },
              com.randioo.shizurongyao_server.protocol.Game.GameAction.class,
              com.randioo.shizurongyao_server.protocol.Game.GameAction.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
