// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Market.proto

package com.randioo.shizurongyao_server.protocol;

public final class Market {
  private Market() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class MarketShowRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use MarketShowRequest.newBuilder() to construct.
    private MarketShowRequest() {
      initFields();
    }
    private MarketShowRequest(boolean noInit) {}
    
    private static final MarketShowRequest defaultInstance;
    public static MarketShowRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketShowRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shizurongyao_server.protocol.Market.internal_static_com_randioo_shizurongyao_server_protocol_MarketShowRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shizurongyao_server.protocol.Market.internal_static_com_randioo_shizurongyao_server_protocol_MarketShowRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest result;
      
      // Construct using com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest();
        return builder;
      }
      
      protected com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest.getDescriptor();
      }
      
      public com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest getDefaultInstanceForType() {
        return com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest) {
          return mergeFrom((com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest other) {
        if (other == com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shizurongyao_server.protocol.MarketShowRequest)
    }
    
    static {
      defaultInstance = new MarketShowRequest(true);
      com.randioo.shizurongyao_server.protocol.Market.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shizurongyao_server.protocol.MarketShowRequest)
  }
  
  public static final class MarketShowResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use MarketShowResponse.newBuilder() to construct.
    private MarketShowResponse() {
      initFields();
    }
    private MarketShowResponse(boolean noInit) {}
    
    private static final MarketShowResponse defaultInstance;
    public static MarketShowResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketShowResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shizurongyao_server.protocol.Market.internal_static_com_randioo_shizurongyao_server_protocol_MarketShowResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shizurongyao_server.protocol.Market.internal_static_com_randioo_shizurongyao_server_protocol_MarketShowResponse_fieldAccessorTable;
    }
    
    // optional bool isRefresh = 1;
    public static final int ISREFRESH_FIELD_NUMBER = 1;
    private boolean hasIsRefresh;
    private boolean isRefresh_ = false;
    public boolean hasIsRefresh() { return hasIsRefresh; }
    public boolean getIsRefresh() { return isRefresh_; }
    
    // optional int32 refreshCount = 2;
    public static final int REFRESHCOUNT_FIELD_NUMBER = 2;
    private boolean hasRefreshCount;
    private int refreshCount_ = 0;
    public boolean hasRefreshCount() { return hasRefreshCount; }
    public int getRefreshCount() { return refreshCount_; }
    
    // optional int32 needMoney = 3;
    public static final int NEEDMONEY_FIELD_NUMBER = 3;
    private boolean hasNeedMoney;
    private int needMoney_ = 0;
    public boolean hasNeedMoney() { return hasNeedMoney; }
    public int getNeedMoney() { return needMoney_; }
    
    // repeated .com.randioo.shizurongyao_server.protocol.MarketItemData marketItemData = 4;
    public static final int MARKETITEMDATA_FIELD_NUMBER = 4;
    private java.util.List<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData> marketItemData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData> getMarketItemDataList() {
      return marketItemData_;
    }
    public int getMarketItemDataCount() { return marketItemData_.size(); }
    public com.randioo.shizurongyao_server.protocol.Entity.MarketItemData getMarketItemData(int index) {
      return marketItemData_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasIsRefresh()) {
        output.writeBool(1, getIsRefresh());
      }
      if (hasRefreshCount()) {
        output.writeInt32(2, getRefreshCount());
      }
      if (hasNeedMoney()) {
        output.writeInt32(3, getNeedMoney());
      }
      for (com.randioo.shizurongyao_server.protocol.Entity.MarketItemData element : getMarketItemDataList()) {
        output.writeMessage(4, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasIsRefresh()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, getIsRefresh());
      }
      if (hasRefreshCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getRefreshCount());
      }
      if (hasNeedMoney()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getNeedMoney());
      }
      for (com.randioo.shizurongyao_server.protocol.Entity.MarketItemData element : getMarketItemDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse result;
      
      // Construct using com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse();
        return builder;
      }
      
      protected com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse.getDescriptor();
      }
      
      public com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse getDefaultInstanceForType() {
        return com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.marketItemData_ != java.util.Collections.EMPTY_LIST) {
          result.marketItemData_ =
            java.util.Collections.unmodifiableList(result.marketItemData_);
        }
        com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse) {
          return mergeFrom((com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse other) {
        if (other == com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse.getDefaultInstance()) return this;
        if (other.hasIsRefresh()) {
          setIsRefresh(other.getIsRefresh());
        }
        if (other.hasRefreshCount()) {
          setRefreshCount(other.getRefreshCount());
        }
        if (other.hasNeedMoney()) {
          setNeedMoney(other.getNeedMoney());
        }
        if (!other.marketItemData_.isEmpty()) {
          if (result.marketItemData_.isEmpty()) {
            result.marketItemData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData>();
          }
          result.marketItemData_.addAll(other.marketItemData_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setIsRefresh(input.readBool());
              break;
            }
            case 16: {
              setRefreshCount(input.readInt32());
              break;
            }
            case 24: {
              setNeedMoney(input.readInt32());
              break;
            }
            case 34: {
              com.randioo.shizurongyao_server.protocol.Entity.MarketItemData.Builder subBuilder = com.randioo.shizurongyao_server.protocol.Entity.MarketItemData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMarketItemData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional bool isRefresh = 1;
      public boolean hasIsRefresh() {
        return result.hasIsRefresh();
      }
      public boolean getIsRefresh() {
        return result.getIsRefresh();
      }
      public Builder setIsRefresh(boolean value) {
        result.hasIsRefresh = true;
        result.isRefresh_ = value;
        return this;
      }
      public Builder clearIsRefresh() {
        result.hasIsRefresh = false;
        result.isRefresh_ = false;
        return this;
      }
      
      // optional int32 refreshCount = 2;
      public boolean hasRefreshCount() {
        return result.hasRefreshCount();
      }
      public int getRefreshCount() {
        return result.getRefreshCount();
      }
      public Builder setRefreshCount(int value) {
        result.hasRefreshCount = true;
        result.refreshCount_ = value;
        return this;
      }
      public Builder clearRefreshCount() {
        result.hasRefreshCount = false;
        result.refreshCount_ = 0;
        return this;
      }
      
      // optional int32 needMoney = 3;
      public boolean hasNeedMoney() {
        return result.hasNeedMoney();
      }
      public int getNeedMoney() {
        return result.getNeedMoney();
      }
      public Builder setNeedMoney(int value) {
        result.hasNeedMoney = true;
        result.needMoney_ = value;
        return this;
      }
      public Builder clearNeedMoney() {
        result.hasNeedMoney = false;
        result.needMoney_ = 0;
        return this;
      }
      
      // repeated .com.randioo.shizurongyao_server.protocol.MarketItemData marketItemData = 4;
      public java.util.List<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData> getMarketItemDataList() {
        return java.util.Collections.unmodifiableList(result.marketItemData_);
      }
      public int getMarketItemDataCount() {
        return result.getMarketItemDataCount();
      }
      public com.randioo.shizurongyao_server.protocol.Entity.MarketItemData getMarketItemData(int index) {
        return result.getMarketItemData(index);
      }
      public Builder setMarketItemData(int index, com.randioo.shizurongyao_server.protocol.Entity.MarketItemData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.marketItemData_.set(index, value);
        return this;
      }
      public Builder setMarketItemData(int index, com.randioo.shizurongyao_server.protocol.Entity.MarketItemData.Builder builderForValue) {
        result.marketItemData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMarketItemData(com.randioo.shizurongyao_server.protocol.Entity.MarketItemData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.marketItemData_.isEmpty()) {
          result.marketItemData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData>();
        }
        result.marketItemData_.add(value);
        return this;
      }
      public Builder addMarketItemData(com.randioo.shizurongyao_server.protocol.Entity.MarketItemData.Builder builderForValue) {
        if (result.marketItemData_.isEmpty()) {
          result.marketItemData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData>();
        }
        result.marketItemData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMarketItemData(
          java.lang.Iterable<? extends com.randioo.shizurongyao_server.protocol.Entity.MarketItemData> values) {
        if (result.marketItemData_.isEmpty()) {
          result.marketItemData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData>();
        }
        super.addAll(values, result.marketItemData_);
        return this;
      }
      public Builder clearMarketItemData() {
        result.marketItemData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shizurongyao_server.protocol.MarketShowResponse)
    }
    
    static {
      defaultInstance = new MarketShowResponse(true);
      com.randioo.shizurongyao_server.protocol.Market.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shizurongyao_server.protocol.MarketShowResponse)
  }
  
  public static final class MarketBuyMarketItemRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use MarketBuyMarketItemRequest.newBuilder() to construct.
    private MarketBuyMarketItemRequest() {
      initFields();
    }
    private MarketBuyMarketItemRequest(boolean noInit) {}
    
    private static final MarketBuyMarketItemRequest defaultInstance;
    public static MarketBuyMarketItemRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketBuyMarketItemRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shizurongyao_server.protocol.Market.internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shizurongyao_server.protocol.Market.internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemRequest_fieldAccessorTable;
    }
    
    // optional int32 index = 1;
    public static final int INDEX_FIELD_NUMBER = 1;
    private boolean hasIndex;
    private int index_ = 0;
    public boolean hasIndex() { return hasIndex; }
    public int getIndex() { return index_; }
    
    // optional int32 buyCount = 2;
    public static final int BUYCOUNT_FIELD_NUMBER = 2;
    private boolean hasBuyCount;
    private int buyCount_ = 0;
    public boolean hasBuyCount() { return hasBuyCount; }
    public int getBuyCount() { return buyCount_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasIndex()) {
        output.writeInt32(1, getIndex());
      }
      if (hasBuyCount()) {
        output.writeInt32(2, getBuyCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasIndex()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getIndex());
      }
      if (hasBuyCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getBuyCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest result;
      
      // Construct using com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest();
        return builder;
      }
      
      protected com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest.getDescriptor();
      }
      
      public com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest getDefaultInstanceForType() {
        return com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest) {
          return mergeFrom((com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest other) {
        if (other == com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest.getDefaultInstance()) return this;
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        if (other.hasBuyCount()) {
          setBuyCount(other.getBuyCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setIndex(input.readInt32());
              break;
            }
            case 16: {
              setBuyCount(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 index = 1;
      public boolean hasIndex() {
        return result.hasIndex();
      }
      public int getIndex() {
        return result.getIndex();
      }
      public Builder setIndex(int value) {
        result.hasIndex = true;
        result.index_ = value;
        return this;
      }
      public Builder clearIndex() {
        result.hasIndex = false;
        result.index_ = 0;
        return this;
      }
      
      // optional int32 buyCount = 2;
      public boolean hasBuyCount() {
        return result.hasBuyCount();
      }
      public int getBuyCount() {
        return result.getBuyCount();
      }
      public Builder setBuyCount(int value) {
        result.hasBuyCount = true;
        result.buyCount_ = value;
        return this;
      }
      public Builder clearBuyCount() {
        result.hasBuyCount = false;
        result.buyCount_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shizurongyao_server.protocol.MarketBuyMarketItemRequest)
    }
    
    static {
      defaultInstance = new MarketBuyMarketItemRequest(true);
      com.randioo.shizurongyao_server.protocol.Market.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shizurongyao_server.protocol.MarketBuyMarketItemRequest)
  }
  
  public static final class MarketBuyMarketItemResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use MarketBuyMarketItemResponse.newBuilder() to construct.
    private MarketBuyMarketItemResponse() {
      initFields();
    }
    private MarketBuyMarketItemResponse(boolean noInit) {}
    
    private static final MarketBuyMarketItemResponse defaultInstance;
    public static MarketBuyMarketItemResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketBuyMarketItemResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shizurongyao_server.protocol.Market.internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shizurongyao_server.protocol.Market.internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional int32 buyCount = 2;
    public static final int BUYCOUNT_FIELD_NUMBER = 2;
    private boolean hasBuyCount;
    private int buyCount_ = 0;
    public boolean hasBuyCount() { return hasBuyCount; }
    public int getBuyCount() { return buyCount_; }
    
    // optional int32 nextBuyMoney = 3;
    public static final int NEXTBUYMONEY_FIELD_NUMBER = 3;
    private boolean hasNextBuyMoney;
    private int nextBuyMoney_ = 0;
    public boolean hasNextBuyMoney() { return hasNextBuyMoney; }
    public int getNextBuyMoney() { return nextBuyMoney_; }
    
    // optional .com.randioo.shizurongyao_server.protocol.MarketItemDataBuyType buyType = 4;
    public static final int BUYTYPE_FIELD_NUMBER = 4;
    private boolean hasBuyType;
    private com.randioo.shizurongyao_server.protocol.Entity.MarketItemDataBuyType buyType_;
    public boolean hasBuyType() { return hasBuyType; }
    public com.randioo.shizurongyao_server.protocol.Entity.MarketItemDataBuyType getBuyType() { return buyType_; }
    
    private void initFields() {
      buyType_ = com.randioo.shizurongyao_server.protocol.Entity.MarketItemDataBuyType.GOLD;
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasBuyCount()) {
        output.writeInt32(2, getBuyCount());
      }
      if (hasNextBuyMoney()) {
        output.writeInt32(3, getNextBuyMoney());
      }
      if (hasBuyType()) {
        output.writeEnum(4, getBuyType().getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasBuyCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getBuyCount());
      }
      if (hasNextBuyMoney()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getNextBuyMoney());
      }
      if (hasBuyType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, getBuyType().getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse result;
      
      // Construct using com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse();
        return builder;
      }
      
      protected com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse.getDescriptor();
      }
      
      public com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse getDefaultInstanceForType() {
        return com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse) {
          return mergeFrom((com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse other) {
        if (other == com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasBuyCount()) {
          setBuyCount(other.getBuyCount());
        }
        if (other.hasNextBuyMoney()) {
          setNextBuyMoney(other.getNextBuyMoney());
        }
        if (other.hasBuyType()) {
          setBuyType(other.getBuyType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 16: {
              setBuyCount(input.readInt32());
              break;
            }
            case 24: {
              setNextBuyMoney(input.readInt32());
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.randioo.shizurongyao_server.protocol.Entity.MarketItemDataBuyType value = com.randioo.shizurongyao_server.protocol.Entity.MarketItemDataBuyType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                setBuyType(value);
              }
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // optional int32 buyCount = 2;
      public boolean hasBuyCount() {
        return result.hasBuyCount();
      }
      public int getBuyCount() {
        return result.getBuyCount();
      }
      public Builder setBuyCount(int value) {
        result.hasBuyCount = true;
        result.buyCount_ = value;
        return this;
      }
      public Builder clearBuyCount() {
        result.hasBuyCount = false;
        result.buyCount_ = 0;
        return this;
      }
      
      // optional int32 nextBuyMoney = 3;
      public boolean hasNextBuyMoney() {
        return result.hasNextBuyMoney();
      }
      public int getNextBuyMoney() {
        return result.getNextBuyMoney();
      }
      public Builder setNextBuyMoney(int value) {
        result.hasNextBuyMoney = true;
        result.nextBuyMoney_ = value;
        return this;
      }
      public Builder clearNextBuyMoney() {
        result.hasNextBuyMoney = false;
        result.nextBuyMoney_ = 0;
        return this;
      }
      
      // optional .com.randioo.shizurongyao_server.protocol.MarketItemDataBuyType buyType = 4;
      public boolean hasBuyType() {
        return result.hasBuyType();
      }
      public com.randioo.shizurongyao_server.protocol.Entity.MarketItemDataBuyType getBuyType() {
        return result.getBuyType();
      }
      public Builder setBuyType(com.randioo.shizurongyao_server.protocol.Entity.MarketItemDataBuyType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasBuyType = true;
        result.buyType_ = value;
        return this;
      }
      public Builder clearBuyType() {
        result.hasBuyType = false;
        result.buyType_ = com.randioo.shizurongyao_server.protocol.Entity.MarketItemDataBuyType.GOLD;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shizurongyao_server.protocol.MarketBuyMarketItemResponse)
    }
    
    static {
      defaultInstance = new MarketBuyMarketItemResponse(true);
      com.randioo.shizurongyao_server.protocol.Market.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shizurongyao_server.protocol.MarketBuyMarketItemResponse)
  }
  
  public static final class MarketArtificialRefreshRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use MarketArtificialRefreshRequest.newBuilder() to construct.
    private MarketArtificialRefreshRequest() {
      initFields();
    }
    private MarketArtificialRefreshRequest(boolean noInit) {}
    
    private static final MarketArtificialRefreshRequest defaultInstance;
    public static MarketArtificialRefreshRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketArtificialRefreshRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shizurongyao_server.protocol.Market.internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shizurongyao_server.protocol.Market.internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest result;
      
      // Construct using com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest();
        return builder;
      }
      
      protected com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest.getDescriptor();
      }
      
      public com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest getDefaultInstanceForType() {
        return com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest) {
          return mergeFrom((com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest other) {
        if (other == com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shizurongyao_server.protocol.MarketArtificialRefreshRequest)
    }
    
    static {
      defaultInstance = new MarketArtificialRefreshRequest(true);
      com.randioo.shizurongyao_server.protocol.Market.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shizurongyao_server.protocol.MarketArtificialRefreshRequest)
  }
  
  public static final class MarketArtificialRefreshResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use MarketArtificialRefreshResponse.newBuilder() to construct.
    private MarketArtificialRefreshResponse() {
      initFields();
    }
    private MarketArtificialRefreshResponse(boolean noInit) {}
    
    private static final MarketArtificialRefreshResponse defaultInstance;
    public static MarketArtificialRefreshResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public MarketArtificialRefreshResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shizurongyao_server.protocol.Market.internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shizurongyao_server.protocol.Market.internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional int32 refreshCount = 2;
    public static final int REFRESHCOUNT_FIELD_NUMBER = 2;
    private boolean hasRefreshCount;
    private int refreshCount_ = 0;
    public boolean hasRefreshCount() { return hasRefreshCount; }
    public int getRefreshCount() { return refreshCount_; }
    
    // optional int32 needMoney = 3;
    public static final int NEEDMONEY_FIELD_NUMBER = 3;
    private boolean hasNeedMoney;
    private int needMoney_ = 0;
    public boolean hasNeedMoney() { return hasNeedMoney; }
    public int getNeedMoney() { return needMoney_; }
    
    // repeated .com.randioo.shizurongyao_server.protocol.MarketItemData marketItemData = 4;
    public static final int MARKETITEMDATA_FIELD_NUMBER = 4;
    private java.util.List<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData> marketItemData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData> getMarketItemDataList() {
      return marketItemData_;
    }
    public int getMarketItemDataCount() { return marketItemData_.size(); }
    public com.randioo.shizurongyao_server.protocol.Entity.MarketItemData getMarketItemData(int index) {
      return marketItemData_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasRefreshCount()) {
        output.writeInt32(2, getRefreshCount());
      }
      if (hasNeedMoney()) {
        output.writeInt32(3, getNeedMoney());
      }
      for (com.randioo.shizurongyao_server.protocol.Entity.MarketItemData element : getMarketItemDataList()) {
        output.writeMessage(4, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasRefreshCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getRefreshCount());
      }
      if (hasNeedMoney()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getNeedMoney());
      }
      for (com.randioo.shizurongyao_server.protocol.Entity.MarketItemData element : getMarketItemDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse result;
      
      // Construct using com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse();
        return builder;
      }
      
      protected com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse.getDescriptor();
      }
      
      public com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse getDefaultInstanceForType() {
        return com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.marketItemData_ != java.util.Collections.EMPTY_LIST) {
          result.marketItemData_ =
            java.util.Collections.unmodifiableList(result.marketItemData_);
        }
        com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse) {
          return mergeFrom((com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse other) {
        if (other == com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasRefreshCount()) {
          setRefreshCount(other.getRefreshCount());
        }
        if (other.hasNeedMoney()) {
          setNeedMoney(other.getNeedMoney());
        }
        if (!other.marketItemData_.isEmpty()) {
          if (result.marketItemData_.isEmpty()) {
            result.marketItemData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData>();
          }
          result.marketItemData_.addAll(other.marketItemData_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 16: {
              setRefreshCount(input.readInt32());
              break;
            }
            case 24: {
              setNeedMoney(input.readInt32());
              break;
            }
            case 34: {
              com.randioo.shizurongyao_server.protocol.Entity.MarketItemData.Builder subBuilder = com.randioo.shizurongyao_server.protocol.Entity.MarketItemData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMarketItemData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // optional int32 refreshCount = 2;
      public boolean hasRefreshCount() {
        return result.hasRefreshCount();
      }
      public int getRefreshCount() {
        return result.getRefreshCount();
      }
      public Builder setRefreshCount(int value) {
        result.hasRefreshCount = true;
        result.refreshCount_ = value;
        return this;
      }
      public Builder clearRefreshCount() {
        result.hasRefreshCount = false;
        result.refreshCount_ = 0;
        return this;
      }
      
      // optional int32 needMoney = 3;
      public boolean hasNeedMoney() {
        return result.hasNeedMoney();
      }
      public int getNeedMoney() {
        return result.getNeedMoney();
      }
      public Builder setNeedMoney(int value) {
        result.hasNeedMoney = true;
        result.needMoney_ = value;
        return this;
      }
      public Builder clearNeedMoney() {
        result.hasNeedMoney = false;
        result.needMoney_ = 0;
        return this;
      }
      
      // repeated .com.randioo.shizurongyao_server.protocol.MarketItemData marketItemData = 4;
      public java.util.List<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData> getMarketItemDataList() {
        return java.util.Collections.unmodifiableList(result.marketItemData_);
      }
      public int getMarketItemDataCount() {
        return result.getMarketItemDataCount();
      }
      public com.randioo.shizurongyao_server.protocol.Entity.MarketItemData getMarketItemData(int index) {
        return result.getMarketItemData(index);
      }
      public Builder setMarketItemData(int index, com.randioo.shizurongyao_server.protocol.Entity.MarketItemData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.marketItemData_.set(index, value);
        return this;
      }
      public Builder setMarketItemData(int index, com.randioo.shizurongyao_server.protocol.Entity.MarketItemData.Builder builderForValue) {
        result.marketItemData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMarketItemData(com.randioo.shizurongyao_server.protocol.Entity.MarketItemData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.marketItemData_.isEmpty()) {
          result.marketItemData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData>();
        }
        result.marketItemData_.add(value);
        return this;
      }
      public Builder addMarketItemData(com.randioo.shizurongyao_server.protocol.Entity.MarketItemData.Builder builderForValue) {
        if (result.marketItemData_.isEmpty()) {
          result.marketItemData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData>();
        }
        result.marketItemData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMarketItemData(
          java.lang.Iterable<? extends com.randioo.shizurongyao_server.protocol.Entity.MarketItemData> values) {
        if (result.marketItemData_.isEmpty()) {
          result.marketItemData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.MarketItemData>();
        }
        super.addAll(values, result.marketItemData_);
        return this;
      }
      public Builder clearMarketItemData() {
        result.marketItemData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shizurongyao_server.protocol.MarketArtificialRefreshResponse)
    }
    
    static {
      defaultInstance = new MarketArtificialRefreshResponse(true);
      com.randioo.shizurongyao_server.protocol.Market.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shizurongyao_server.protocol.MarketArtificialRefreshResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shizurongyao_server_protocol_MarketShowRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shizurongyao_server_protocol_MarketShowRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shizurongyao_server_protocol_MarketShowResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shizurongyao_server_protocol_MarketShowResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Market.proto\022(com.randioo.shizurongyao" +
      "_server.protocol\032\014Entity.proto\"\023\n\021Market" +
      "ShowRequest\"\242\001\n\022MarketShowResponse\022\021\n\tis" +
      "Refresh\030\001 \001(\010\022\024\n\014refreshCount\030\002 \001(\005\022\021\n\tn" +
      "eedMoney\030\003 \001(\005\022P\n\016marketItemData\030\004 \003(\01328" +
      ".com.randioo.shizurongyao_server.protoco" +
      "l.MarketItemData\"=\n\032MarketBuyMarketItemR" +
      "equest\022\r\n\005index\030\001 \001(\005\022\020\n\010buyCount\030\002 \001(\005\"" +
      "\255\001\n\033MarketBuyMarketItemResponse\022\024\n\terror" +
      "Code\030\001 \001(\005:\0011\022\020\n\010buyCount\030\002 \001(\005\022\024\n\014nextB",
      "uyMoney\030\003 \001(\005\022P\n\007buyType\030\004 \001(\0162?.com.ran" +
      "dioo.shizurongyao_server.protocol.Market" +
      "ItemDataBuyType\" \n\036MarketArtificialRefre" +
      "shRequest\"\262\001\n\037MarketArtificialRefreshRes" +
      "ponse\022\024\n\terrorCode\030\001 \001(\005:\0011\022\024\n\014refreshCo" +
      "unt\030\002 \001(\005\022\021\n\tneedMoney\030\003 \001(\005\022P\n\016marketIt" +
      "emData\030\004 \003(\01328.com.randioo.shizurongyao_" +
      "server.protocol.MarketItemData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_shizurongyao_server_protocol_MarketShowRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_shizurongyao_server_protocol_MarketShowRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shizurongyao_server_protocol_MarketShowRequest_descriptor,
              new java.lang.String[] { },
              com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest.class,
              com.randioo.shizurongyao_server.protocol.Market.MarketShowRequest.Builder.class);
          internal_static_com_randioo_shizurongyao_server_protocol_MarketShowResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_shizurongyao_server_protocol_MarketShowResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shizurongyao_server_protocol_MarketShowResponse_descriptor,
              new java.lang.String[] { "IsRefresh", "RefreshCount", "NeedMoney", "MarketItemData", },
              com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse.class,
              com.randioo.shizurongyao_server.protocol.Market.MarketShowResponse.Builder.class);
          internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemRequest_descriptor,
              new java.lang.String[] { "Index", "BuyCount", },
              com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest.class,
              com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemRequest.Builder.class);
          internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shizurongyao_server_protocol_MarketBuyMarketItemResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "BuyCount", "NextBuyMoney", "BuyType", },
              com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse.class,
              com.randioo.shizurongyao_server.protocol.Market.MarketBuyMarketItemResponse.Builder.class);
          internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshRequest_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshRequest_descriptor,
              new java.lang.String[] { },
              com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest.class,
              com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshRequest.Builder.class);
          internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshResponse_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shizurongyao_server_protocol_MarketArtificialRefreshResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "RefreshCount", "NeedMoney", "MarketItemData", },
              com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse.class,
              com.randioo.shizurongyao_server.protocol.Market.MarketArtificialRefreshResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.shizurongyao_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
