// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rank.proto

package com.randioo.shizurongyao_server.protocol;

public final class Rank {
  private Rank() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class RankShowClanPointRankRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use RankShowClanPointRankRequest.newBuilder() to construct.
    private RankShowClanPointRankRequest() {
      initFields();
    }
    private RankShowClanPointRankRequest(boolean noInit) {}
    
    private static final RankShowClanPointRankRequest defaultInstance;
    public static RankShowClanPointRankRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RankShowClanPointRankRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shizurongyao_server.protocol.Rank.internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shizurongyao_server.protocol.Rank.internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankRequest_fieldAccessorTable;
    }
    
    // optional int32 clanId = 1;
    public static final int CLANID_FIELD_NUMBER = 1;
    private boolean hasClanId;
    private int clanId_ = 0;
    public boolean hasClanId() { return hasClanId; }
    public int getClanId() { return clanId_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasClanId()) {
        output.writeInt32(1, getClanId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasClanId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getClanId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest result;
      
      // Construct using com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest();
        return builder;
      }
      
      protected com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest.getDescriptor();
      }
      
      public com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest getDefaultInstanceForType() {
        return com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest) {
          return mergeFrom((com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest other) {
        if (other == com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest.getDefaultInstance()) return this;
        if (other.hasClanId()) {
          setClanId(other.getClanId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setClanId(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 clanId = 1;
      public boolean hasClanId() {
        return result.hasClanId();
      }
      public int getClanId() {
        return result.getClanId();
      }
      public Builder setClanId(int value) {
        result.hasClanId = true;
        result.clanId_ = value;
        return this;
      }
      public Builder clearClanId() {
        result.hasClanId = false;
        result.clanId_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shizurongyao_server.protocol.RankShowClanPointRankRequest)
    }
    
    static {
      defaultInstance = new RankShowClanPointRankRequest(true);
      com.randioo.shizurongyao_server.protocol.Rank.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shizurongyao_server.protocol.RankShowClanPointRankRequest)
  }
  
  public static final class RankShowClanPointRankResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use RankShowClanPointRankResponse.newBuilder() to construct.
    private RankShowClanPointRankResponse() {
      initFields();
    }
    private RankShowClanPointRankResponse(boolean noInit) {}
    
    private static final RankShowClanPointRankResponse defaultInstance;
    public static RankShowClanPointRankResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RankShowClanPointRankResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shizurongyao_server.protocol.Rank.internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shizurongyao_server.protocol.Rank.internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankResponse_fieldAccessorTable;
    }
    
    // repeated .com.randioo.shizurongyao_server.protocol.PointRankData pointRankData = 1;
    public static final int POINTRANKDATA_FIELD_NUMBER = 1;
    private java.util.List<com.randioo.shizurongyao_server.protocol.Entity.PointRankData> pointRankData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.shizurongyao_server.protocol.Entity.PointRankData> getPointRankDataList() {
      return pointRankData_;
    }
    public int getPointRankDataCount() { return pointRankData_.size(); }
    public com.randioo.shizurongyao_server.protocol.Entity.PointRankData getPointRankData(int index) {
      return pointRankData_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.randioo.shizurongyao_server.protocol.Entity.PointRankData element : getPointRankDataList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.randioo.shizurongyao_server.protocol.Entity.PointRankData element : getPointRankDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse result;
      
      // Construct using com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse();
        return builder;
      }
      
      protected com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse.getDescriptor();
      }
      
      public com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse getDefaultInstanceForType() {
        return com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.pointRankData_ != java.util.Collections.EMPTY_LIST) {
          result.pointRankData_ =
            java.util.Collections.unmodifiableList(result.pointRankData_);
        }
        com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse) {
          return mergeFrom((com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse other) {
        if (other == com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse.getDefaultInstance()) return this;
        if (!other.pointRankData_.isEmpty()) {
          if (result.pointRankData_.isEmpty()) {
            result.pointRankData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.PointRankData>();
          }
          result.pointRankData_.addAll(other.pointRankData_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.shizurongyao_server.protocol.Entity.PointRankData.Builder subBuilder = com.randioo.shizurongyao_server.protocol.Entity.PointRankData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPointRankData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.randioo.shizurongyao_server.protocol.PointRankData pointRankData = 1;
      public java.util.List<com.randioo.shizurongyao_server.protocol.Entity.PointRankData> getPointRankDataList() {
        return java.util.Collections.unmodifiableList(result.pointRankData_);
      }
      public int getPointRankDataCount() {
        return result.getPointRankDataCount();
      }
      public com.randioo.shizurongyao_server.protocol.Entity.PointRankData getPointRankData(int index) {
        return result.getPointRankData(index);
      }
      public Builder setPointRankData(int index, com.randioo.shizurongyao_server.protocol.Entity.PointRankData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.pointRankData_.set(index, value);
        return this;
      }
      public Builder setPointRankData(int index, com.randioo.shizurongyao_server.protocol.Entity.PointRankData.Builder builderForValue) {
        result.pointRankData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPointRankData(com.randioo.shizurongyao_server.protocol.Entity.PointRankData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.pointRankData_.isEmpty()) {
          result.pointRankData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.PointRankData>();
        }
        result.pointRankData_.add(value);
        return this;
      }
      public Builder addPointRankData(com.randioo.shizurongyao_server.protocol.Entity.PointRankData.Builder builderForValue) {
        if (result.pointRankData_.isEmpty()) {
          result.pointRankData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.PointRankData>();
        }
        result.pointRankData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPointRankData(
          java.lang.Iterable<? extends com.randioo.shizurongyao_server.protocol.Entity.PointRankData> values) {
        if (result.pointRankData_.isEmpty()) {
          result.pointRankData_ = new java.util.ArrayList<com.randioo.shizurongyao_server.protocol.Entity.PointRankData>();
        }
        super.addAll(values, result.pointRankData_);
        return this;
      }
      public Builder clearPointRankData() {
        result.pointRankData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shizurongyao_server.protocol.RankShowClanPointRankResponse)
    }
    
    static {
      defaultInstance = new RankShowClanPointRankResponse(true);
      com.randioo.shizurongyao_server.protocol.Rank.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shizurongyao_server.protocol.RankShowClanPointRankResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRank.proto\022(com.randioo.shizurongyao_s" +
      "erver.protocol\032\014Entity.proto\".\n\034RankShow" +
      "ClanPointRankRequest\022\016\n\006clanId\030\001 \001(\005\"o\n\035" +
      "RankShowClanPointRankResponse\022N\n\rpointRa" +
      "nkData\030\001 \003(\01327.com.randioo.shizurongyao_" +
      "server.protocol.PointRankData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankRequest_descriptor,
              new java.lang.String[] { "ClanId", },
              com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest.class,
              com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankRequest.Builder.class);
          internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shizurongyao_server_protocol_RankShowClanPointRankResponse_descriptor,
              new java.lang.String[] { "PointRankData", },
              com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse.class,
              com.randioo.shizurongyao_server.protocol.Rank.RankShowClanPointRankResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.shizurongyao_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
